### ISSUE TITLE
Changing pngs to vector

### ISSUE THREAD

**Issue by avipars** [shuli81/shemesh#1]
If you would change the png files to vector, it would save the use a lot of space on the phone. This can be done very easily, if you use the default icons, which the share button does. 

It generated the same share button in an xml file, and the code looks like this, also not much code needs to be changed: 

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FF000000"
        android:pathData="M18,16.08c-0.76,0 -1.44,0.3 -1.96,0.77L8.91,12.7c0.05,-0.23 0.09,-0.46 0.09,-0.7s-0.04,-0.47 -0.09,-0.7l7.05,-4.11c0.54,0.5 1.25,0.81 2.04,0.81 1.66,0 3,-1.34 3,-3s-1.34,-3 -3,-3 -3,1.34 -3,3c0,0.24 0.04,0.47 0.09,0.7L8.04,9.81C7.5,9.31 6.79,9 6,9c-1.66,0 -3,1.34 -3,3s1.34,3 3,3c0.79,0 1.5,-0.31 2.04,-0.81l7.12,4.16c-0.05,0.21 -0.08,0.43 -0.08,0.65 0,1.61 1.31,2.92 2.92,2.92 1.61,0 2.92,-1.31 2.92,-2.92s-1.31,-2.92 -2.92,-2.92z"/>
</vector>
`
I can create a pull request, if you don't understand the issue.

**Comment by shuli81** [comment]
done.

**Comment by avipars** [comment]
Great, Can't wait for an update!

**Comment by shuli81** [comment]
Tomorrow hopefully. Too tired :)
